# Project 2
## Matthew Manno's Data

I will use this data to figure out geographically where my users are. I want to know where they are located by city, and if city is unavailable then by the state they live in.

I Want to know:

    1. What city has the largest number of female users.
    2. What city has the largest number of male users.
    3. What state has the largest number of female users.
    4. What state has the largest number of male users.

In [34]:
import numpy as np
import pandas as pd
#set some pandas options controling output format
pd.set_option('display.notebook_repr_html',True) # output as flat text and not HTML
pd.set_option('display.max_rows', None) # this is the maximum number of rows we will display
pd.set_option('display.max_columns', None) # this is the maximum number of rows we will display

In [35]:
# read the csv into a dataframe, and force postal_code to be interpreted as a string.
users = pd.read_csv('data/IS-362_Untidy_Data.csv', dtype={'postal_code': str})

In [36]:
# Display the columns in the dataframe, and get a peak at how it's formatted
users.head()

,id,first_name,last_name,gender,email,address,city,state,postal_code,phone_number
0,1,Loralee,MacAdam,NaN,lmacadam0@twitter.com,0122 Alpine Street,Fort Wayne,Indiana,46814,260-134-3027
1,2,Shir,Padula,Female,spadula1@state.gov,7 Orin Lane,Littleton,Colorado,NaN,720-172-5365
2,3,Nicole,Ottey,Female,nottey2@ucsd.edu,04558 Del Mar Street,New York City,New York,10175,646-968-2745
3,4,Wandie,MacKinnon,Female,wmackinnon3@geocities.jp,4 Morningstar Alley,Tucson,Arizona,85743,520-484-3593
4,5,NaN,Avey,Male,tavey4@google.com.br,40574 Mallard Crossing,Canton,Ohio,44720,234-345-6985

In [37]:
# get rid of rows without a city, state, and postal code
users.dropna(subset=['city', 'state', 'postal_code'], how='all', inplace=True)

In [38]:
# create a dataframe with the number of female users by State. Dropping NaN state values.
state_users = users.dropna(subset=['state'], how='any') \
                [(users.dropna(subset=['state'], how='any').gender == 'Female')] \
                .groupby('state') \
                .state.count() \
                .reset_index(name='female_count') \
                .sort_values(['state'], ascending=True)

# create a dataframe with the number of male users by State. Dropping NaN state values.
male_users = users.dropna(subset=['state'], how='any') \
                [(users.dropna(subset=['state'], how='any').gender == 'Male')] \
                .groupby('state') \
                .state.count() \
                .reset_index(name='male_count') \
                .sort_values(['state'], ascending=True)

# join the two series into one dataframe
state_users = state_users.join(male_users.male_count)

In [39]:
# return the state with the most female users
state_users.sort_values('female_count', ascending=False).head(1)

        state  female_count  male_count
4  California            57          39

In [40]:
# return the state with the most male users
state_users.sort_values('male_count', ascending=False).head(1)

        state  female_count  male_count
4  California            57          39

In [41]:
# create a dataframe with the number of female users by city
city_users = users.dropna(subset=['city'], how='any') \
                [(users.dropna(subset=['city'], how='any').gender == 'Female')] \
                .groupby(['city', 'state']) \
                .city.count() \
                .reset_index(name='female_count') \
                .sort_values(['city','state'], ascending=[True,True])

# create a dataframe with the number of male users by city
male_users = users.dropna(subset=['city'], how='any') \
                [(users.dropna(subset=['city'], how='any').gender == 'Male')] \
                .groupby(['city','state']) \
                .city.count() \
                .reset_index(name='male_count') \
                .sort_values(['city', 'state'], ascending=[True,True])
                
# join the two series into one dataframe
city_users = city_users.join(male_users.male_count)
city_users.male_count = male_users.male_count.astype(int)

In [42]:
# return the city with the most female users
city_users.sort_values('female_count', ascending=False).head(1)

           city                 state  female_count  male_count
203  Washington  District of Columbia            20         NaN

In [43]:
# return the city with the most male users
city_users.sort_values('male_count', ascending=False).head(1)

      city    state  female_count  male_count
188  Tampa  Florida             2        18.0

## Matthew Manno's Answers
to answer my questions:
    1. What city has the largest number of female users.
                Washington, DC
    2. What city has the largest number of male users.
                Tampa, FL
    3. What state has the largest number of female users.
                California
    4. What state has the largest number of male users.
                California

# Djamshed Djuraev's Data
Djamshed's post:
    I have found the following CSV formatted data which is called "Death_Rates_NYC". Here is the CSV file: Death_Rates_NYC.csv 

    Here is what I will be analyzing by using pandas:

    1. There is dot's exist in the some rows which is a missing data. I will change the dot's to null and will sort the data by Year and Leading Cause.
    2. I will see all causes of death among females of white non Hispanic Race Ethnicity.
    3. I will filter data by grouping by Race Ethnicity and sort the data by Race Ethnicity and Leading Cause.

In [44]:
# read the csv into a dataframe, and set all "." to na values
dot = pd.read_csv('data/Death_Rates_NYC.csv', na_values=['.'])

In [45]:
dot.head(5)

,Year,Leading Cause,Sex,Race Ethnicity,Deaths,Death Rate,Age Adjusted Death Rate
0,2014,Diabetes Mellitus (E10-E14),F,Other Race/ Ethnicity,11.0,NaN,NaN
1,2011,Cerebrovascular Disease (Stroke: I60-I69),M,White Non-Hispanic,290.0,21.7,18.2
2,2008,Malignant Neoplasms (Cancer: C00-C97),M,Not Stated/Unknown,60.0,NaN,NaN
3,2010,Malignant Neoplasms (Cancer: C00-C97),F,Hispanic,1045.0,85.9,98.5
4,2012,Cerebrovascular Disease (Stroke: I60-I69),M,Black Non-Hispanic,170.0,19.9,23.3

In [46]:
# rename the columns for ease of use
dot = dot.rename(columns={'Year': 'year', \
                          'Leading Cause': 'leading_cause', \
                          'Sex': 'sex', \
                          'Race Ethnicity': 'race_ethnicity', \
                          'Deaths': 'deaths', \
                          'Death Rate': 'death_rate', \
                          'Age Adjusted Death Rate': 'age_adjusted_death_rate'})

# this line drops any rows with null for Year, Leading Cause, or Deaths.
dot.dropna(subset=['year', 'leading_cause', 'deaths'], how='any', inplace=True) 

# set the deaths column to integers so pandas interprets it numerically
dot.deaths = dot.deaths.astype(int)

In [47]:
# Sort the dataframe by Year and Leading Cause... which means total deaths for a leading cause.
dot.sort_values(['year', 'deaths'], ascending=[True, False], inplace=True)

In [48]:
# Filter the dataframe to show only deaths for White Non-Hispanic females.
f_wnh_deaths = dot[(dot.race_ethnicity == 'White Non-Hispanic') & (dot.sex == 'F')]
            
f_wnh_deaths.head(50)

,year,leading_cause,sex,race_ethnicity,deaths,death_rate,age_adjusted_death_rate
234,2007,All Other Causes,F,White Non-Hispanic,1680,117.1,81.5
181,2007,"Accidents Except Drug Posioning (V01-X39, X43,...",F,White Non-Hispanic,162,11.3,7.3
230,2008,All Other Causes,F,White Non-Hispanic,1706,118.9,78.6
38,2008,Diabetes Mellitus (E10-E14),F,White Non-Hispanic,210,14.6,8.8
190,2009,Malignant Neoplasms (Cancer: C00-C97),F,White Non-Hispanic,3346,232.9,159.0
119,2010,"Diseases of Heart (I00-I09, I11, I13, I20-I51)",F,White Non-Hispanic,5351,374.2,189.2
224,2010,Chronic Lower Respiratory Diseases (J40-J47),F,White Non-Hispanic,501,35.0,20.7
133,2010,Essential Hypertension and Renal Diseases (I10...,F,White Non-Hispanic,219,15.3,7.7
195,2011,Malignant Neoplasms (Cancer: C00-C97),F,White Non-Hispanic,3371,238.0,161.1
165,2011,Essential Hypertension and Renal Diseases (I10...,F,White Non-Hispanic,199,14.0,6.8
27,2011,Mental and Behavioral Disorders due to Acciden...,F,White Non-Hispanic,88,6.2,6.1
226,2012,Diabetes Mellitus (E10-E14),F,White Non-Hispanic,240,16.9,10.3
115,2012,Essential Hypertension and Renal Diseases (I10...,F,White Non-Hispanic,199,14.0,7.2
285,2012,"Accidents Except Drug Posioning (V01-X39, X43,...",F,White Non-Hispanic,177,12.5,8.5
218,2013,"Diseases of Heart (I00-I09, I11, I13, I20-I51)",F,White Non-Hispanic,4535,319.0,160.6
239,2013,All Other Causes,F,White Non-Hispanic,2595,182.5,111.1
147,2013,Influenza (Flu) and Pneumonia (J09-J18),F,White Non-Hispanic,622,43.7,22.1
243,2013,Cerebrovascular Disease (Stroke: I60-I69),F,White Non-Hispanic,427,30.0,16.4
104,2013,Alzheimer's Disease (G30),F,White Non-Hispanic,263,18.5,8.4
282,2013,"Accidents Except Drug Posioning (V01-X39, X43,...",F,White Non-Hispanic,166,11.7,8.1
129,2014,Influenza (Flu) and Pneumonia (J09-J18),F,White Non-Hispanic,563,39.7,20.4
23,2014,Essential Hypertension and Renal Diseases (I10...,F,White Non-Hispanic,180,12.7,6.7
28,2014,"Accidents Except Drug Posioning (V01-X39, X43,...",F,White Non-Hispanic,169,11.9,7.4
223,2014,Septicemia (A40-A41),F,White Non-Hispanic,118,8.3,4.7

In [49]:
# I will filter data by grouping by Race Ethnicity and sort the data by Race Ethnicity and Leading Cause.
# I think what he is trying to say is that he will sort the data in such a way that he will be able
# to discren the leading cause of death by race/ethnicity. To do this we furst have to create a 
# dataframe that holds the race/ethnicity, leading cause of death, and sum of those deaths from each year.
# this line of code does that.
leading_cause_by_race = dot.groupby(['race_ethnicity', 'leading_cause'], \
                        as_index=False)['deaths'].sum()

In [50]:
# Then we take the dataframe with the race/ethnicity, leading cause of death, and sum of those 
# deaths from each year, and sort it by race/ethnicity, and the sum of the Leading cause of death.
leading_cause_by_race.sort_values(['race_ethnicity', 'deaths'], ascending=[True,False])

,race_ethnicity,leading_cause,deaths
11,Asian and Pacific Islander,Malignant Neoplasms (Cancer: C00-C97),3263
1,Asian and Pacific Islander,All Other Causes,1743
7,Asian and Pacific Islander,"Diseases of Heart (I00-I09, I11, I13, I20-I51)",1730
9,Asian and Pacific Islander,Influenza (Flu) and Pneumonia (J09-J18),429
2,Asian and Pacific Islander,Cerebrovascular Disease (Stroke: I60-I69),391
5,Asian and Pacific Islander,Chronic Lower Respiratory Diseases (J40-J47),286
0,Asian and Pacific Islander,"Accidents Except Drug Posioning (V01-X39, X43,...",168
6,Asian and Pacific Islander,Diabetes Mellitus (E10-E14),128
8,Asian and Pacific Islander,Essential Hypertension and Renal Diseases (I10...,92
10,Asian and Pacific Islander,"Intentional Self-Harm (Suicide: X60-X84, Y87.0)",58
12,Asian and Pacific Islander,"Nephritis, Nephrotic Syndrome and Nephrisis (N...",41
3,Asian and Pacific Islander,Certain Conditions originating in the Perinata...,19
4,Asian and Pacific Islander,"Chronic Liver Disease and Cirrhosis (K70, K73)",17
13,Asian and Pacific Islander,Viral Hepatitis (B15-B19),15
21,Black Non-Hispanic,"Diseases of Heart (I00-I09, I11, I13, I20-I51)",12661
25,Black Non-Hispanic,Malignant Neoplasms (Cancer: C00-C97),6865
15,Black Non-Hispanic,All Other Causes,4182
20,Black Non-Hispanic,Diabetes Mellitus (E10-E14),2394
18,Black Non-Hispanic,Cerebrovascular Disease (Stroke: I60-I69),987
17,Black Non-Hispanic,"Assault (Homicide: Y87.1, X85-Y09)",832
19,Black Non-Hispanic,Chronic Lower Respiratory Diseases (J40-J47),673
22,Black Non-Hispanic,Essential Hypertension and Renal Diseases (I10...,657
14,Black Non-Hispanic,"Accidents Except Drug Posioning (V01-X39, X43,...",599
23,Black Non-Hispanic,Human Immunodeficiency Virus Disease (HIV: B20...,596
24,Black Non-Hispanic,Influenza (Flu) and Pneumonia (J09-J18),537
16,Black Non-Hispanic,Alzheimer's Disease (G30),257
26,Black Non-Hispanic,Mental and Behavioral Disorders due to Acciden...,163
27,Black Non-Hispanic,"Nephritis, Nephrotic Syndrome and Nephrisis (N...",90
28,Black Non-Hispanic,Septicemia (A40-A41),89
40,Hispanic,Malignant Neoplasms (Cancer: C00-C97),6743
36,Hispanic,"Diseases of Heart (I00-I09, I11, I13, I20-I51)",5176
30,Hispanic,All Other Causes,2187
35,Hispanic,Diabetes Mellitus (E10-E14),1235
38,Hispanic,Human Immunodeficiency Virus Disease (HIV: B20...,852
39,Hispanic,Influenza (Flu) and Pneumonia (J09-J18),822
29,Hispanic,"Accidents Except Drug Posioning (V01-X39, X43,...",603
32,Hispanic,Cerebrovascular Disease (Stroke: I60-I69),595
33,Hispanic,"Chronic Liver Disease and Cirrhosis (K70, K73)",403
41,Hispanic,Mental and Behavioral Disorders due to Acciden...,311
34,Hispanic,Chronic Lower Respiratory Diseases (J40-J47),307
37,Hispanic,Essential Hypertension and Renal Diseases (I10...,300
31,Hispanic,Alzheimer's Disease (G30),246
42,Hispanic,Septicemia (A40-A41),49
44,Not Stated/Unknown,All Other Causes,608
55,Not Stated/Unknown,Malignant Neoplasms (Cancer: C00-C97),170
51,Not Stated/Unknown,"Diseases of Heart (I00-I09, I11, I13, I20-I51)",158
47,Not Stated/Unknown,Certain Conditions originating in the Perinata...,66
53,Not Stated/Unknown,Influenza (Flu) and Pneumonia (J09-J18),32
49,Not Stated/Unknown,Chronic Lower Respiratory Diseases (J40-J47),28
56,Not Stated/Unknown,Mental and Behavioral Disorders due to Acciden...,28
46,Not Stated/Unknown,Cerebrovascular Disease (Stroke: I60-I69),22
52,Not Stated/Unknown,Human Immunodeficiency Virus Disease (HIV: B20...,15
43,Not Stated/Unknown,"Accidents Except Drug Posioning (V01-X39, X43,...",10
48,Not Stated/Unknown,"Chronic Liver Disease and Cirrhosis (K70, K73)",10
54,Not Stated/Unknown,"Intentional Self-Harm (Suicide: X60-X84, Y87.0)",8
45,Not Stated/Unknown,"Assault (Homicide: Y87.1, X85-Y09)",7
50,Not Stated/Unknown,Diabetes Mellitus (E10-E14),5
57,Other Race/ Ethnicity,All Other Causes,260
67,Other Race/ Ethnicity,Malignant Neoplasms (Cancer: C00-C97),122
62,Other Race/ Ethnicity,"Diseases of Heart (I00-I09, I11, I13, I20-I51)",40
61,Other Race/ Ethnicity,Diabetes Mellitus (E10-E14),20
58,Other Race/ Ethnicity,Cerebrovascular Disease (Stroke: I60-I69),19
66,Other Race/ Ethnicity,"Intentional Self-Harm (Suicide: X60-X84, Y87.0)",15
65,Other Race/ Ethnicity,Influenza (Flu) and Pneumonia (J09-J18),13
68,Other Race/ Ethnicity,Mental and Behavioral Disorders due to Acciden...,12
59,Other Race/ Ethnicity,"Chronic Liver Disease and Cirrhosis (K70, K73)",10
64,Other Race/ Ethnicity,Human Immunodeficiency Virus Disease (HIV: B20...,10
63,Other Race/ Ethnicity,Essential Hypertension and Renal Diseases (I10...,8
69,Other Race/ Ethnicity,Septicemia (A40-A41),6
60,Other Race/ Ethnicity,Chronic Lower Respiratory Diseases (J40-J47),5
80,White Non-Hispanic,Malignant Neoplasms (Cancer: C00-C97),13481
71,White Non-Hispanic,All Other Causes,11582
76,White Non-Hispanic,"Diseases of Heart (I00-I09, I11, I13, I20-I51)",9886
78,White Non-Hispanic,Influenza (Flu) and Pneumonia (J09-J18),1687
75,White Non-Hispanic,Diabetes Mellitus (E10-E14),1278
73,White Non-Hispanic,Cerebrovascular Disease (Stroke: I60-I69),1247
77,White Non-Hispanic,Essential Hypertension and Renal Diseases (I10...,1240
74,White Non-Hispanic,Chronic Lower Respiratory Diseases (J40-J47),1234
70,White Non-Hispanic,"Accidents Except Drug Posioning (V01-X39, X43,...",971
79,White Non-Hispanic,"Intentional Self-Harm (Suicide: X60-X84, Y87.0)",586
72,White Non-Hispanic,Alzheimer's Disease (G30),263
82,White Non-Hispanic,Septicemia (A40-A41),118
81,White Non-Hispanic,Mental and Behavioral Disorders due to Acciden...,88

# Nicholas Ileczko 's Data
Nicholas's post:
    This dataset contains traffic violation information from all electronic traffic violations issued in the County.
    https://catalog.data.gov/dataset/traffic-violations-56dda

    1. I will analyze the data by finding out which type of car has the most violations
    2. Which state besides Maryland has the highest violations
    3. Which violation is most popular

The dataset provided was over 400 MB, so I truncated is significantly to only the first 1000 rows, for the purpsoses of this assignment.

In [65]:
# dot = pd.read_csv('data/Death_Rates_NYC.csv', na_values=['.'])
traffic = pd.read_csv('data/Traffic_Violations_Short.csv', dtype={'Year': str})

In [66]:
# create a series that contains the year, make, and model in one string
ymm = traffic['Year'].astype(str) + ' ' + traffic['Make'] + ' ' + traffic['Model']

In [67]:
ymm.head(1000)

0                         2008 FORD 4S
1                  2001 TOYOTA COROLLA
2                    2001 HONDA ACCORD
3                     1998 DODG DAKOTA
4                  2015 MINI COOPER 2S
5                 2013 HYUNDAI ELANTRA
6                     1993 FORD PICKUP
7                  2003 DODGE SPRINTER
8                  2015 MINI COOPER 2S
9                  2015 MINI COOPER 2S
10                       2005 CADI STS
11                    1996 HONDA CIVIC
12               2004 CHEVROLET IMPALA
13                        2005 AUDI 4S
14                        2002 TOYT 4S
15                  2009 DODGE CHARGER
16                      2000 SATURN LS
17                   2003 HONDA ACCORD
18                 2015 MINI COOPER 2S
19                   2005 TOYOTA CAMRY
20                 2015 MINI COOPER 2S
21                 2002 FORD ECONOLINE
22                 2015 MINI COOPER 2S
23                       1991 LEXUS 4S
24                    2005 FORD ESCAPE
25                        2004 ACUR 4S
26                        2012 GILL HY
27                  2005 CADI ESCALADE
28                       nan NONE NONE
29                    2005 FORD ESCAPE
30                   2008 HONDA ACCORD
31                   2008 HONDA ACCORD
32                       nan NONE NONE
33                        2011 AUDI S5
34                   2006 MERCEDEZ SUV
35                  2008 BUICK ENCLAVE
36                   2006 MERCEDEZ SUV
37                   2006 MERCEDEZ SUV
38                    2000 CHEV MALIBU
39                 2012 KAWASAKI NINJA
40                      2013 ACURA SUV
41                   2000 HONDA ACCORD
42                       2012 JEEP 4X4
43                      2008 FORD F150
44                     2008 TOYT RAV 4
45             2004 MITSUBISHI GALLANT
46                   2006 MERCEDEZ SUV
47                  2001 FORD EXPLORER
48                 2003 FORD EXCURSION
49                    2002 HONDA CIVIC
50                   2012 SUNNY NINGBO
51                2000 FORD EXPEDITION
52                2000 FORD EXPEDITION
53                2007 LINCOLN MARK LT
54                     1996 HOND CIVIC
55                   2001 TOYOTA RAV 4
56                  1997 FORD EXPLORER
57                   2001 CHRY SEBRING
58                       2002 INFI G35
59                 2000 SUBARU OUTBACK
60                   1998 TOYOTA CAMRY
61                2000 FORD EXPEDITION
62                2000 FORD EXPEDITION
63                2000 FORD EXPEDITION
64                      2005 GMC YUKON
65                    1999 HONDA CIVIC
66                   2012 TOYOTA CAMRY
67                    2003 LEXUS GS300
68                        2011 MAZDA 2
69                         2007 BMW 4S
70                  2013 HYUNDA TUCSON
71                        1997 HOND 4S
72                        1999 NISS 4S
73                       2005 WV JETTA
74                       1999 HONDA 2S
75                1998 FORD EXPEDITION
76             1998 CHEVROLET CAVALIER
77                      1996 HONDA CIV
78                        2011 NISS 4S
79                        2011 NISS 4S
80                        2011 NISS 4S
81                  1994 DODGE PICK UP
82                 2002 HOND ACCORD 4S
83                        2007 PONT 4S
84                        2013 AUDI 4S
85                    2009 TOYOT PRIUS
86                   2013 CHRYSLER 200
87                    2004 HONDA PILOT
88                  1996 FORD EXPLORER
89                 2000 TOYOTA COROLLA
90                        1996 OLDS 4S
91              2001 FORD TK EXPLPORER
92                        2011 NISS 4S
93                     2017 SUBARU STI
94                    1999 LEXUS ES300
95                   2002 TOYT COROLLA
96                     2017 SUBARU STI
97                  2008 NISSAN SENTRA
98                        2016 TOYT TK
99                        2016 TOYT TK
100              2002 CHEVROLET BLAZER
101                     2013 HONDA 4DR
102                   2006 DODGE TRUCK
103                      2003 LNDR SUV
104                       2006 NISS 4S
105                  2006 FORD MUSTANG
106                 2010 TOYOTA TACOMA
107                 2011 CHEVY EQUINOX
108                       2016 TOYT TK
109                       2016 TOYT TK
110                  2014 JEEP COMPASS
111                       2016 TOYT TK
112                 2013 DODGE DURANGO
113                    2003 SATURN SUV
114                       2016 TOYT TK
115                  1996 TOYOTA CAMRY
116                       2003 LINC TK
117                       2016 TOYT TK
118                 2010 BUICK LUCERNE
119                   2004 CHEVY ASTRO
120               1997 SUBRARU IMPREZA
121              2006 CHEVY IMPALA  LT
122             2007 TOYOTA HIGHLANDER
123                       1996 CHEV TK
124                 2015 LANDROVER HSE
125                2000 DODGE INTREPID
126                   2014 TOY COROLLA
127                 2010 INFINITI FX35
128                       2016 TOYT TK
129             2006 CHRYSLER PACIFICA
130                  2006 FORD MUSTANG
131                   1999 FORD RANGER
132                      2014 JEEP 4X4
133                 1998 MERCURY GABLE
134                 2011 NISSAN ALTIMA
135                1995 TOYOTA 4RUNNER
136                 1990 ACURA INTEGRA
137                      1999 JEEP TRK
138               2010 HYUNDAI ELANTRA
139                2005 FORD CROWN VIC
140                    2007 CHEVY 2500
141                     2003 TOYOTA 2D
142                2001 TOYOTA SEQUUIA
143                     2008 MAZDA RX8
144                   2005 CHEV MALIBU
145                   2005 CHEV MALIBU
146                            0 XX XX
147                2006 HOND CIVIC  4S
148                       2007 FORD CV
149                  2007 CHEVY IMPALA
150                      2006 BMW 325I
151                    2009 NISS VERSA
152                  1999 HONDA ACCORD
153                   2005 CHEV MALIBU
154                       2002 DODG 4S
155                       1996 CHEV 4S
156                 2002 BUICK CENTURY
157                       2002 DODG 4S
158                       2002 DODG 4S
159                       1999 SAAB 93
160                   1997 HONDA CIVIC
161                       2008 CADI TK
162                   2006 LEXUS GS300
163                     2004 ACURA RSX
164             2010 TOYOTA HIGHLANDER
165                       2000 FORD TK
166                       2002 TOYT 4D
167                   1999 CHEV MALIBU
168             2002 NISSAN PATHFINDER
169                2014 TOYOTA COROLLA
170                2014 TOYOTA COROLLA
171                2014 TOYOTA COROLLA
172                  2002 DODG STRATUS
173                2014 TOYOTA COROLLA
174                       2011 NISS TK
175                1994 TOYOTA COROLLA
176                     2009 HONDA FIT
177           2014 JEEP GRAND CHEROKEE
178                  2007 TOYOTA YARIS
179                     1990 LEXUS 4DR
180                   1999 FORD RANGER
181                     2012 CRUZ CRUZ
182                  2008 HONDA ACCORD
183                   1998 HOND ACCORD
184                2014 TOYOTA COROLLA
185                     2003 FORD E250
186              2002 NISSAN SENTRA 4D
187                    2013 HOND PILOT
188                   2013 HONDA CIVIC
189                       2005 FORD VN
190                    2017 SUBARU WRX
191                       2003 BMW 4DR
192                     2004 ACURA 4DR
193                2014 HYANDAI SONATA
194                  2004 HONDA ACCORD
195            2007 FORD EXPLORER SPTR
196                  2006 CHRY SEBRING
197                       2013 HYUN 4S
198                  2008 KIA SPECTRA5
199                    2009 TOYOTA SUV
200                  2016 TOYOYTA TAXI
201                 2006 TOYOTA SIENNA
202                    2017 TOYOTA 4DR
203                 1998 NISSAN MAXIMA
204                  1998 TOYOTA CAMRY
205                   2009 CHEV MALIBU
206                  2012 LEXUS ES 350
207                   1998 HONDA CIVIC
208                  2012 TOYOTA CAMRY
209                  1996 HONDA ACCORD
210                2011 NISSAN ALTIMOA
211                  2000 HONDA ACCORD
212                 1999 TOYOTA SIENNA
213                       2014 BMW 4DR
214                 1998 FORD EXPLORER
215                 2007 CHEVY EQUINOX
216                2001 HOND ACCORD 4S
217                  1998 DODGE DAKOTA
218                   2013 HONDA CIVIC
219              2009 CHRYSLER SEBRING
220                  2006 HYUN ELANTRA
221              1994 CHRYSLER LEBARON
222                2000 FORD BOX TRUCK
223                     2007 HUMMER H3
224                     2002 GMC YUKON
225                  2012 HONDA ACCORD
226                       2004 CHEV TK
227                      1996 BUICK 4S
228                  2007 MERCEDES SUV
229                     2004 CHEVY VAN
230            2001 MITSUBUSHI MONTERO
231                       2003 MERC 4S
232                 2014 JEEP CHEROKEE
233                       2013 KIA RIO
234                   2007 LEXUS RX350
235                  2002 INFINITI I35
236            2007 NISS 350 Z TRICKED
237                  2014 HONDA ACCORD
238                   1998 HONDA CIVIC
239                2006 HYUNDAI SONATA
240                       2000 MERZ TK
241            2007 NISS 350 Z TRICKED
242                  2012 HONDA ACCORD
243               1996 LINC 4S TOWNCAR
244                       2005 MAZDA 3
245                       1998 TOYT 4D
246                2016 TOYOTA COROLLA
247                   2007 HONDA CIVIC
248                  1997 TOYOTA CAMRY
249                      1994 JEEP SUV
250                  1998 TOYT COROLLA
251                  1994 FORD PICK UP
252                  2011 FORD MUSTANG
253                2008 HYUNDAI ACCENT
254                  2008 TOYOTA CAMRY
255                  2014 HONDA SCCORD
256                      2007 LEXUS 4S
257                       2007 HOND 4S
258                      2004 BUICK 4S
259                      2002 ACURA 4D
260            1999 CHEVROLET SUBURBAN
261                  2008 SATU OUTLOOK
262                      2006 SCION TC
263                     1995 FORD F150
264                      2009 HONDA VN
265                 2007 BUICK LUCERNE
266           2002 MERCURY MOUNTAINEER
267                 2012 MERCEDES C300
268                       2015 CHEV CN
269                  2005 CHEVY IMPALA
270                   2003 FORD ESCAPE
271                       2014 MAZDA 3
272                      2014 DODGE TK
273                       2000 CHEV TK
274                   2012 CHEVY CRUZE
275                       2008 BUIC 4S
276                   2012 CHEVY CRUZE
277                       2013 FORD 4D
278                2010 TOYOTA COROLLA
279                 2003 CHEV TRAVERSE
280                2001 TOYOTA COROLLA
281                 2005 NISSAN SENTRA
282                2003 TOYOTA COROLLA
283                       2006 AUDI 4S
284                       2001 HOND 4S
285                   2007 FORD TAURUS
286                2001 FORD CROWN VIC
287                 2003 FORD EXPLORER
288                2002 TOYOTA 4RUNNER
289                2008 TOYOTA COROLLA
290                     2006 ACURA MDX
291                       2002 JEEP SW
292                   2009 HONDA CIVIC
293                  2005 CHRYSLER 300
294                       2006 CHRY 4S
295                  2004 TOYOTA CAMRY
296                       2001 LINC 4S
297                    2004 FORD TRUCK
298                       2007 DODG VN
299           2004 CHRYSLER PT CRUISER
300                       2009 VOLK 4S
301         2006 RANGE ROVER SPORT HSE
302                       2006 HYUN 4S
303                     2008 MAZDA CX7
304                 2003 FORD EXPLORER
305                  2007 CHRYSLER 300
306                       2003 NISS 4S
307                  2003 TOYOTA CAMRY
308                   1997 HONDA CIVIV
309                  2011 TOYOTA CAMRY
310                       2007 TOYT 4S
311                   2014 HONDA CIVIC
312                2002 TOYOTA CORROLA
313                        2007 MAZD 3
314             1995 TOYT COROLLA - 4S
315                  2002 CHEVROLET TK
316                 2004 TOYOTA SOLARA
317                     0 MITS ECLIPSE
318                    2003 ACUR SUMDX
319                  2010 CHEVY COBALT
320                       2004 HOND CP
321                       2003 SUBA SW
322               2008 HYUNDAI ELANTRA
323                2011 MITSUBISHI SUV
324                       2005 CHRY 2S
325                  2014 NISSAN QUEST
326                 2003 TOYOTA TACOMA
327                      2002 BMW 325I
328               1997 PLYMOUTH BREEZE
329                2012 TOYOTA COROLLA
330                  2004 FORD EXPLORE
331                      2003 CHRY VAN
332                   2007 HOND ACCORD
333                       2010 HOND 2S
334             2011 M BENZ C300 SEDAN
335                  2010 TOYOTA CAMRY
336                   2011 FORD FUSION
337                  2010 TOYOTA SIENA
338                      2011 BMW 550I
339             2000 CHEVROLET EXPRESS
340              2009 DODGE CHALLENGER
341                   2007 HONDA CIVIC
342                   2006 HONDA PILOT
343                  2004 TOYT COROLLA
344                       2004 FORD TK
345                 2006 NISSAN SENTRA
346             2005 FORD EXPLORER XLT
347                   2000 TOYT SIENNA
348                       2003 HOND SU
349                       2005 FORD TK
350                   2001 TOYT AVALON
351                       1996 TOYT 4S
352                  2002 GMC YUKON XL
353             2011 TOYOTA HIGHLANDER
354                      1999 ACURA 4D
355                       2014 TOYT 2S
356                       2011 TOYT 4S
357                       2010 HYUN 2S
358                   1997 HONDA CIVIC
359                2013 KAW MOTORCYCLE
360                       2006 ACUR 2S
361                   1990 HONDA CIVIC
362                     2006 TOYOTA TK
363                 2001 NISSAN ALTIMA
364               2005 CHEVEROLET AVEO
365               2004 2004 MITSUBISHI
366                        2001 BMW 4S
367                       2002 CHRY VN
368                      2012 JEEP 4X4
369                2004 TOYOTA SEQUOIA
370                       2001 SAAB 4S
371                       2005 CHEV 4S
372                        2007 BMW 2S
373                       2013 TOYT SU
374               2015 UNKNOWN UNKNOWN
375                    1999 CHEV TAHOE
376                   2006 HONDA CIVIC
377                       2015 TOYT SW
378                       1997 TOYT 4S
379                       2011 HYUN TK
380                     2015 SUBARU SW
381                     2015 SUBARU SW
382                     2015 SUBARU SW
383                       2017 FORD 4D
384                3003 HYNDAI ELANTRA
385                     2010 TOYT RAV4
386                 2000 ACURA INTEGRA
387                     2002 FORD F150
388                      2007 JEEP SUV
389                     2009 FORD FLEX
390                     2010 TOYT RAV4
391                  2006 TOYOTA CAMRY
392                    2004 FORD TRUCK
393                  1994 TOYOTA CAMRY
394                 1998 TOYOTA TACOMA
395              2005 CHEV TRAILBLAZER
396                       2017 FORD 4D
397                      2016 ACURA 4D
398                       2011 TOYT VN
399                   2000 HONDA CIVIC
400                  2006 TOYT COROLLA
401                      1999 FORD P/U
402                2010 TOYOTA COROLLA
403                 1998 DODGE CARAVAN
404                       2004 TOYT VN
405                 1996 MAZDA PROTEGE
406                2005 TOYOTA 4RUNNER
407                 2005 FORD EXPLORER
408               2011 HYUNDAI ELANTRA
409                  1999 TOYOTA CAMRY
410                      2000 ACURA 4S
411                  2011 HYUN ELANRTA
412                      2000 ACURA 4S
413                  2007 HONDA ACCORD
414               1997 FORD EXPEDITION
415                      2002 JEEP SUV
416              2011 VOLKSWAGON JETTA
417                 2012 TOYOTA SIENNA
418                 2000 INFINITY Q45T
419                  1997 HONDA ACCORD
420                2011 TOYOTA 4RUNNER
421                    1994 CHEV PRISM
422           2010 DODGE CHALLENGER 2D
423              2002 NISSAN SENTRA 4D
424                  2006 FORD MUSTANG
425                  2006 FORD MUSTANG
426                  2006 FORD MUSTANG
427                  2006 FORD MUSTANG
428         2005 CHEVROLET TRAILBLAZER
429                       1997 HOND 4S
430            2010 MERC GRAND MARQUIS
431                 2002 ACURA INTEGRA
432               1997 DODGE RAM WAGON
433                       2004 HOND TK
434                       2007 FORD TK
435            2007 NISS 350 Z TRICKED
436                 1997 NISSAN MAXIMA
437            2007 NISS 350 Z TRICKED
438                    2006 FORD TRUCK
439               1996 LINC 4S TOWNCAR
440                2002 TOYOTA COROLLA
441               1996 LINC 4S TOWNCAR
442                2016 TOYOTA COROLLA
443                2016 TOYOTA COROLLA
444                  2003 HONDA ACCORD
445                     2013 MERZ C250
446                     2010 MERZ C300
447                      1997 LEXUS TK
448                2016 TOYOTA COROLLA
449         2005 NEW FLYER RIDE ON BUS
450         2005 NEW FLYER RIDE ON BUS
451                     2017 VOLKS 4DR
452                    2013 CHEV CRUZE
453                  2009 CADI ESCLADE
454                      2017 FORD SUV
455                   1999 CHEV LUMINA
456                  2005 HONDA ACCORD
457                 2012 MERCEDEZ E350
458                 1994 FORD AEROSTAR
459        1996 OLDSMOBILE EIGHTYEIGHT
460             2008 TOYOTA FJ CRUISER
461                       2004 FORD TK
462                  1999 HONDA ACCORD
463                  1999 HONDA ACCORD
464                  1999 HONDA ACCORD
465               2009 HYUNDAI ELANTRA
466               2009 HYUNDAI ELANTRA
467                 1999 MERCURY SABLE
468                     1988 CHEV MONT
469                     2011 HONDA FIT
470                    2010 FORD FOCUS
471                 2002 TOYOTA SIENNA
472                     2006 HONDA CRV
473                   2003 HONDA CIVIC
474                 2001 MERCEDES C320
475                  2005 HONDA ACCORD
476                       2009 TOYT 4S
477               2012 CHEVROLET SEDAN
478                  2006 MERC CLK 350
479               2012 CHEVROLET SEDAN
480                 2006 NISSAN ALTIMA
481           2009 HONDA ODYSSEY (VAN)
482                      2005 ACURA 2S
483                       2006 MAZD 4S
484               2005 HYUNDAI ELANTRA
485                      nan NONE NONE
486              2011 HYUNDAI SANTA FE
487                 2005 NISSAN MAXIMA
488                      2002 MERZ SUV
489                 2006 NISSAN ALTIMA
490                   2015 FORD FIESTA
491                   2015 FORD FIESTA
492                       2011 TOYT SU
493              2017 VOLKSWAGON JETTA
494              2017 VOLKSWAGON JETTA
495                      2008 ACURA 4S
496                   2005 NISS SENTRA
497                       2002 FORD TK
498                   1997 HONDA CIVIC
499             1996 FORD WINDSTAR VAN
500                       2006 AUDI A6
501                      1998 MERZ 4 D
502                  1996 ACURA 2.5 TL
503                     2013 HONDA FIT
504                  2008 TOYOTA CAMRY
505                  2008 TOYOTA CAMRY
506                       2000 HOND 4S
507                    2009 PONTIAC GT
508                    1995 TOYT CAMRY
509                       2011 JEEP TK
510                 1998 DODGE DURANGO
511                       2001 AUDI A8